### ISSUE TITLE
Alternativa definición padding

### ISSUE THREAD

**Issue by vicenlu** [marmorrei/Sprint-2#2]
También se puede definir así este estilo:

  `  'padding: 2rem 4rem 2rem 4rem;'->  'padding: 2rem 4rem;'`
       

https://github.com/marmorrei/Sprint-2/blob/b4c77b1711a3e84a81806c9d80515436c6e451bc/sass/custom.scss#L53

**Comment by marmorrei** [comment]
Cierto, ¡gracias!
